### ISSUE TITLE
ci_profiler_bar is not defined

### ISSUE THREAD

**Issue by JonoB** [lonnieezell/codeigniter-forensics#1]
I've just started getting a really strange error that I cant pin down. The actual bar works fine, but when clicking on any of the items, I get the following error in FF console:

ci_profiler_bar is not defined
onclick()1 (line 2)
event = click clientX=1179, clientY=573
[Break On This Error] ci_profiler_bar.show("ci-profiler-console", "ci-profiler-menu-console");

**Comment by mckaygerhard** [comment]
this was already fixed in current master and this issue must be closed
